# Generated by Django 3.1.13 on 2022-01-20 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcommentmodel',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
