# Generated by Django 3.1.13 on 2022-01-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220116_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
