# Generated by Django 3.1.13 on 2022-01-17 13:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
